name: ServerStories
main: io.andrewward2001.serverstories.main
version: 1.3
commands:
   serverstory:
      description: The story of this server!
      usage:
      permission: serverstories.story
      permission-message: You don't have enough permissions! Ask for perm serverstories.story